name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latex deps
      run: sudo apt-get install -y texlive-lang-italian texlive-latex-base
    - name: Run python script
      run: python .github/workflows/build_latex.py
    - name: Push build
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Build latex"
          git push
