name: Build & Deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build_latex:
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latex deps
      run: sudo apt-get install -y texlive-lang-italian texlive-latex-full
    - name: Run python script
      run: python build_latex.py
    - name: Push build
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Build latex"
          git push