name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latex deps
      run: sudo apt-get install -y texlive-lang-italian texlive-latex-extra
    - name: Run latex build
      run: python .github/workflows/build_latex.py
    - name: Run html build
      run: python .github/workflows/build_html.py
    - name: Push
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "CI build"
          git push
